---
abstract: 'Perl interface to the Bintray API'
author:
  - 'Mithun Ayachit <mithun@cpan.org>'
build_requires:
  Test::Deep: 0
  Test::More: 0
  Test::Pod: 1.00
  version: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132510'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bintray-API
no_index:
  directory:
    - '.author'
    - '.t'
    - examples
provides:
  Bintray::API:
    file: lib/Bintray/API.pm
    version: 0.01
  Bintray::API::Package:
    file: lib/Bintray/API/Package.pm
    version: 0.01
  Bintray::API::Repo:
    file: lib/Bintray/API/Repo.pm
    version: 0.01
  Bintray::API::Search:
    file: lib/Bintray/API/Search.pm
    version: 0.01
  Bintray::API::Session:
    file: lib/Bintray/API/Session.pm
    version: 0.01
  Bintray::API::Subject:
    file: lib/Bintray/API/Subject.pm
    version: 0.01
  Bintray::API::Version:
    file: lib/Bintray/API/Version.pm
    version: 0.01
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Bintray-API
  homepage: https://github.com/mithun/perl-bintray-api
  license: http://dev.perl.org/licenses/
  repository: git://github.com/mithun/perl-bintray-api.git
version: 0.01
